// #####  Generated by Paletton.com (c) 2002-2014
export const zcolors = [[
    //Red
    '#AA3939', 	/* Main Primary color */
    '#FFAAAA',
    '#D46A6A',
    '#801515',
    '#550000'
],[
    // Blue 
    '#2D4571',	/* Main Primary color */
    '#A9B9D6',
    '#5D739C',
    '#0E2246',
    '#020B1B'
]]